/*HORUS – Filtragem, sem filtrar por tempo - HEPC*/

SELECT * FROM TB_ESPELHO_DISPENSACAO
WHERE ( CO_PRODUTO IN ('10988','11033','10815','10984','10995', '07756', '10975') OR DS_PRODUTO IN ('SOFOSBUVIR ','DACLATASVIR ','SIMEPREVIR ','OMBITASVIR ','VERUPREVIR ', 'RITONAVIR ', 'DASABUVIR ')
OR DS_PRINCIPIO_ATIVO_MEDICAMENTO IN ('SOFOSBUVIR ','DACLATASVIR ','SIMEPREVIR ','OMBITASVIR ','VERUPREVIR ', 'RITONAVIR ', 'DASABUVIR ')
);